language: rust
cache: cargo

os:
  - linux
#  - osx

rust: stable

script:
  - cargo build && (cargo run --example demo || true) && cargo run --example trace && cargo test

env:
- RUST_BACKTRACE=pretty
