language: rust
cache: cargo

os:
  - linux
#  - osx

rust: stable

script:
  - cd unwind && cargo build && (cargo run --example demo || true) && cargo run --example trace

env:
- RUST_BACKTRACE=pretty
