[profile.release]
debug = true

[profile.bench]
debug = true

[workspace]
members = ["unwind"]

#[patch.crates-io]
#gimli = { git = 'https://github.com/main--/gimli.git?branch=unwind-patches' }
[replace]
"gimli:0.14.0" = { git = 'https://github.com/main--/gimli.git', branch = 'unwind-patches' }
