[package]
name = "unwind"
version = "0.1.0"
authors = ["main() <main@ehvag.de>"]

[dependencies]
gimli = "0.18"
libc = "0.2"
fallible-iterator = "0.1"
log = "0.4"

[build-dependencies]
cc = "1.0.35"

[dev-dependencies]
backtrace = "0.3"
env_logger = "0.6"

[features]
nightly = []
asm = ["nightly"]
